language: python
python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9-dev
    - pypy
    - pypy3
install:
    - pip install coverage coveralls
    - pip install -e .[test,bcrypt]
script:
    - coverage run $(which pytest)
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
