language: python
dist: xenial
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - pypy3
matrix:
     include:
        - python: "pypy"
          env: CRYPTOGRAPHY_ALLOW_OPENSSL_102=1
install:
    - pip install coverage coveralls
    - pip install -e .[test,bcrypt]
script:
    - coverage run $(which pytest)
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
